version: '3.7'

services:
  
  backend:
    image: yassinegaaloul/flask-backend:latest  
    ports:
      - "5000:5000"  
    networks:
      - app-network
    environment:
      - FLASK_APP=app.py  
      - FLASK_RUN_HOST=0.0.0.0  
      - MONGO_URI=mongodb://mongo:27017/mediatheque  
    depends_on:
      - mongo  


  frontend:
    image: yassinegaaloul/react-frontend 
    ports:
      - "80:80"  
    networks:
      - app-network
    depends_on:
      - backend  

  
  mongo:
    image: mongo:latest  
    volumes:
      - mongo-data:/data/db  
    networks:
      - app-network
    ports:
      - "27017:27017"  


volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge  
